version: "3"

services:
  grafana:
    image: grafana/grafana:6.2.1
    ports:
      - 3000:3000
    links:
      - boot-influxdb
    volumes:
      - /var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

  influxdb:
    image: influxdb:1.7.6-alpine
    ports:
      - 8086:8086
    volumes:
      - /var/lib/influxdb
    environment:
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: pass
      INFLUXDB_DB: boot
